apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: boutique-frontend
  namespace: boutique
spec:
  to:
    kind: Service
    name: frontend-external
    weight: 100
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
